'use strict';mix_d("P13NSCCards__p13n-rvi:p13n-rvi__2PdP5UV2","exports tslib @p/A @c/metrics @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/a-carousel-framework @c/logger @c/aui-untrusted-ajax @c/browser-operations".split(" "),function(F,u,L,B,M,N,O,P,Q,R,S,T){function x(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var p=x(L),U=x(M),V=x(O),v=x(P),W=x(Q),z=x(R),X=x(S),Y=x(T),G={},C=function(a,c,b){void 0===c&&(c="");void 0===b&&(b=1);c=a+c;G.hasOwnProperty(c)||(G[c]=
!0,B.count(a,(B.count(a)||0)+b))},Z=function(a){C(p["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var c=function(d,e){d={$event:{preventDefault:p["default"].$.noop,stopPropagation:p["default"].$.noop},$target:d.getContent().find('[data-a-tab-name="'+e+'"]'),data:{name:"energyEfficiencyTabSet"}};p["default"].trigger("a:declarative:a-tabs:click",d)},b=function(d,e){var h=d&&d.$event,f=d&&d.data||{},n=f.activeTabName,l=f.modalHeight,q=f.name;
h&&h.preventDefault&&h.preventDefault();h&&h.stopPropagation&&h.stopPropagation();h=e.get(q);h||(p["default"].on("a:popover:beforeShow:"+q,function(g){g.popover&&g.popover.getContent&&(g=g.popover.getContent(),g.find(".a-manually-loaded").parent().css("min-height",l),p["default"].loadDescendantImagesManually(g))}),h=e.create(d.$target,f));h.show();c(h,n)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(d){p["default"].declarative("card-energy-efficiency-secondary-view",
"click",function(e){C("Card:EERU:SharedLib:mobile:click",e&&e.data&&e.data.name||"");b(e,d)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(d){p["default"].declarative("card-energy-efficiency-modal","click",function(e){C("Card:EERU:SharedLib:desktop:click",e&&e.data&&e.data.name||"");b(e,d)})})},aa=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(c){var b=p["default"].$;b(".energyEfficiencyContainer").each(function(d,e){d=b(e).find(".energyEfficiencyProductFicheLabel").first();
e=b(e).find("svg").first();d.parent().outerHeight()>e.outerHeight()&&(d.removeClass("a-size-small"),d.addClass("a-size-micro"),d.parent().outerHeight()>e.outerHeight()&&d.parent().css("line-height","10px"))})})},ba={ctiList:["Website/Personalization/Report a Problem CX"],category:"Website",type:"Personalization",item:"Report a Problem CX",folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",group:"P13N Report a Problem CX"},ca=[{ctiList:["Website/Personalization/Similarities","Website/Detail Page/Similarities"],
category:"Website",type:"Personalization",item:"Similarities",folder:"4d16d05d-9a17-4b36-b8fe-9ee159ff81de",group:"Similarities"}],ha=function(a){var c=v["default"].cardRoot.querySelector(".p13n-report-flag"),b=Y["default"].setup();b.define("showFlag","mouseover",function(){c.classList.remove("p13n-report-flag-hide")});b.define("hideFlag","mouseout",function(){c.classList.add("p13n-report-flag-hide")});b.attach("showFlag",a);b.attach("hideFlag",a);var d=v["default"].cardRoot.querySelector(".internal-flag-form"),
e=d.querySelector(".internal-flag-env-data").dataset,h=d.querySelector(".internal-flag-title-text"),f=d.querySelector(".internal-flag-description").firstElementChild,n=d.querySelector(".internal-flag-alias"),l=d.querySelector(".internal-flag-response-message"),q=function(g){g.preventDefault();g=function(r){return!r||!r.trim()};if(g(h.value)||g(f.value)||g(n.value))return D(l,!1,"Something went wrong. One of the required fields was missing."),!1;g=v["default"].cardRoot.querySelectorAll(".a-dynamic-image");
var k;if(k=v["default"].cardRoot.querySelector(".a-carousel-heading")){var t=da(a,g.length);k="Internal user reported issue '"+h.value+"' with widget: "+k.innerText}else t=ea(a),k="Internal user reported issue '"+h.value+"'";g=fa(g,t,f.value,n.value,e);var m=ba;ca.forEach(function(r){r.ctiList.includes(e.cti)&&(m=r)});X["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:m.folder,
description:g,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:m.group,category:m.category,impact:5,item:m.item,type:m.type}},tags:[{id:"internal-problem-generated"}],title:k}}).then(function(r){D(l,!0,r)}).catch(function(r){D(l,!1,r)});return!1};d.onsubmit=function(g){return q(g)};b=v["default"].cardRoot.querySelector(".p13n-desktop-report-problem-flag-data");if(b.dataset.name)p["default"].on("a:popover:hide:"+b.dataset.name,function(){d.reset();l.innerText=""})},da=function(a,
c){if(!a.dataset.aCarouselOptions)return z["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=v["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(d){return JSON.parse(d).id}).slice(b,b+c)},ea=function(a){return(a=a.dataset.asinList)?a.split(","):[]},fa=function(a,c,b,d,e){for(var h="",f=0;f<a.length;f++){var n=a[f];h+=(n?"![]("+n.src+")":
"IMAGE MISSING")+"\nASIN: "+(c[f]?c[f]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+(d+"](https://phonetool.amazon.com/users/"+d+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+e.widgetGroupId+"\n**Strategy ID:** "+e.strategyId+"\n**CTI:** "+e.cti+"\n**Facets:** ")+
(e.facets+"\n**Content Reftag:** "+e.reftag+"\n"+(""!==e.baseAsin?"**Page ASIN:** "+e.baseAsin+"\n":"")+"\n**SessionID:** ")+(e.sessionId+"\n**MarketplaceID:** "+e.marketplaceId+"\n**Device Type:** "+e.deviceType+"\n\n**List of ASINs:**\n\n")+h},D=function(a,c,b){c?(a.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?a.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+
'" target="_blank">SIM-T ticket</a> you created.':(z["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket."):(z["default"].log("The response body of response data is not an object.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket.")):(a.classList.add("a-color-error"),a.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},
ia={setupModal:function(a){return u.__awaiter(void 0,void 0,void 0,function(){var c;return u.__generator(this,function(b){c=v["default"].cardRoot.querySelector(".p13n-report-problem-modal-root");if(!c)return[2];ha(a);return[2]})})}},H=[],ja=function(a){var c=Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));c.push(a);c.forEach(function(b){if(b&&b.dataset&&b.dataset.metrics&&(!b.id||!H.includes(b.id))){var d=JSON.parse(b.dataset.metrics),e;for(e in d)d.hasOwnProperty(e)&&B.count(e,d[e]);
b.removeAttribute("data-metrics");b.id&&H.push(b.id)}})},I=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,J=/[^\/\-\[\]():\s]/,ka=function(a){var c=p["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||"2",10),d=function(){var f=a.innerHTML;a.innerHTML="&hellip;";var n=a.clientHeight;a.innerHTML=f;return n}();
if(b){if(d){var e=function(f){c.innerHTML=f;return Math.round(c.clientHeight/d)<=b},h=function(f,n){f=f.split(n);var l=Math.floor(a.clientWidth/12),q=function(k){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";c.textContent=k;a.appendChild(c);k=a.clientWidth>=a.scrollWidth;a.removeChild(c);return k},g=function(k){var t=k.length-l;k.trim().length>l&&!q(k)&&Array.prototype.slice.call(k).map(function(m,r){return r>l&&r<=t&&J.test(m)?"&shy;"+m:m});return k};return f.map(function(k){return g(k)}).join("")};
return{truncate:function(){var f=a.innerHTML.trim(),n=a.textContent||"";f=h(f,I);a.appendChild(c);if(e(f))a.removeChild(c),a.innerHTML=f;else{var l=f.split(I);for(var q=1,g=l.length,k,t,m=0;q!==g;)if(k=Math.floor((g+q)/2),t=l.slice(0,k).join("")+"&hellip;",e(t)){if(1>=g-k){for(m=k;0<m&&!J.test(l[m-1]);)m--;break}q=k}else g=k;l=0===m?void 0:l.slice(0,m).join("")+"&hellip;";l?(a.innerHTML=l,a.setAttribute("title",n),a.setAttribute("aria-label",n)):(z["default"].log("Unable to successfully truncate line "+
f,"ERROR"),a.removeChild(c))}}}}z["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else z["default"].log("Truncation element missing necessary line number data","ERROR")},la=function(a){var c=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp","1")?c:c.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var d=
ka(b);d&&(d.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},ma=function(a){var c="slide";a.querySelectorAll(".a-carousel-viewport").forEach(function(b){b&&(b=b.getAttribute("aria-roledescription"),null!==b&&(c=b))});a.querySelectorAll(".a-carousel-card").forEach(function(b){b&&b.setAttribute("aria-roledescription",c)})},sa={initCarousel:function(a){return u.__awaiter(void 0,
void 0,void 0,function(){var c,b,d;return u.__generator(this,function(e){c=(a||{}).afterPageLoaded;b=v["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[v["default"].cardRoot]:Array.prototype.slice.call(v["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));d=V["default"].setup(["getCarouselItems"]);if(null===b||void 0===b||!b.length)return[2];b.forEach(function(h){return u.__awaiter(void 0,void 0,void 0,function(){var f,n,l,q,g;return u.__generator(this,function(k){switch(k.label){case 0:f=
function(){p["default"].loadDynamicImage("[data-name]='"+g+"' .p13n-sc-dynamic-image");la(h);ja(h);null===c||void 0===c?void 0:c(h);var t=window.P;Z(t);aa(t);ma(h)};f();if(h.classList.contains("p13n-carousel-initialized"))return[2];h.classList.add("p13n-carousel-initialized");n=W["default"].getCarousel(N.unscope(h));l=U["default"].getCarousel(h);q=h.dataset||{};g=n.getAttr("name");return[4,Promise.all([l.initialized,ia.setupModal(h)])];case 1:return k.sent(),p["default"].on("a:carousel:"+g+":change:pageSize",
f),p["default"].on("a:carousel:"+g+":change:loading",f),p["default"].on("a:carousel:"+g+":change:animating",f),p["default"].on("a:carousel:"+g+":change:fetchedItems",f),l.attachRemoteOperation(function(t){var m=t.indexes;t=t.ids;var r=d,na=r.getCarouselItems,oa=u.__assign,pa=u.__assign({},q),qa=String(m[0]||0);var ra=m[0]||0,y,E,K=0,w=q.aCarouselOptions?q.aCarouselOptions:void 0;if(w&&(w=JSON.parse(w),w=null===(y=null===w||void 0===w?void 0:w.ajax)||void 0===y?void 0:y.id_list))for(y=0;y<ra&&y<w.length;y++){var A=
JSON.parse(w[y]);"true"===((null===(E=null===A||void 0===A?void 0:A.metadataMap)||void 0===E?0:E.isSponsoredProduct)?A.metadataMap.isSponsoredProduct:"false")&&(K+=1)}return na.call(r,oa.call(u,pa,{ids:t,indexes:m,offset:qa,adOffset:K}))}),[2]}})})});return[2]})})}};F._operationNames=["getCarouselItems"];F.card=function(){return u.__awaiter(void 0,void 0,void 0,function(){return u.__generator(this,function(a){switch(a.label){case 0:return[4,sa.initCarousel()];case 1:return a.sent(),[2]}})})}});
